# Generated by Django 5.1.6 on 2025-02-25 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
        ('usermodel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='sales_contact',
            field=models.ForeignKey(limit_choices_to={'role__name': 'Sales'}, on_delete=django.db.models.deletion.CASCADE, related_name='client_sales_contact', to='usermodel.customusers'),
        ),
    ]
