# Generated by Django 5.1.6 on 2025-02-27 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_initial'),
        ('usermodel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='sales_contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_sales_contact', to='usermodel.customusers'),
        ),
    ]
