# Generated by Django 5.1.6 on 2025-02-27 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0002_initial'),
        ('usermodel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('contract_status', models.CharField(choices=[('Open', 'Open'), ('Signed', 'Signed')], default='Open', max_length=15)),
                ('amount', models.FloatField()),
                ('payment_due', models.DateTimeField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_id', to='client.client')),
                ('sales_contact', models.ForeignKey(limit_choices_to={'role__name': 'Sales'}, on_delete=django.db.models.deletion.CASCADE, related_name='contract_sales_contact', to='usermodel.customusers')),
            ],
        ),
    ]
