# Generated by Django 5.1.6 on 2025-02-27 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contract', '0001_initial'),
        ('usermodel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('event_completed', models.BooleanField(default=False)),
                ('attendees', models.IntegerField(blank=True, null=True)),
                ('event_date', models.DateTimeField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_id', to='contract.contract')),
                ('support_contact', models.ForeignKey(limit_choices_to={'role__name': 'Support'}, on_delete=django.db.models.deletion.CASCADE, related_name='event_support_contact', to='usermodel.customusers')),
            ],
        ),
    ]
